# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161219_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_key',
            field=models.CharField(default='kdsfjskdjfksdf', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
